# Generated by Django 2.1.5 on 2019-03-08 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='岗位名称')),
                ('unit', models.CharField(max_length=200, verbose_name='用工单位')),
                ('desc', models.CharField(max_length=300, verbose_name='岗位描述')),
                ('detail', models.TextField(default='', verbose_name='岗位详情')),
                ('people', models.IntegerField(default=0, verbose_name='报名人数')),
                ('image', models.ImageField(upload_to='job/%Y/%m', verbose_name='封面')),
                ('do_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='上岗时间')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '工作岗位',
                'verbose_name_plural': '工作岗位',
            },
        ),
    ]
