# Generated by Django 2.1.5 on 2019-03-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='price',
            field=models.IntegerField(default=0, verbose_name='岗位薪资'),
        ),
    ]
