# Generated by Django 2.1.5 on 2019-03-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_userjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_type',
            field=models.IntegerField(choices=[(1, '课程'), (2, '课程机构'), (3, '讲师'), (4, '工作岗位')], default=1, verbose_name='收藏类型'),
        ),
    ]
