# Generated by Django 2.1.5 on 2019-03-01 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_remove_course_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='detail',
            field=models.TextField(default='', verbose_name='课程详情'),
        ),
    ]
