# Generated by Django 2.1.5 on 2019-03-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190225_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='salary',
            field=models.IntegerField(default=0, verbose_name='个人薪资'),
        ),
    ]
