# Generated by Django 2.1.5 on 2019-03-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stu_academy',
            field=models.CharField(default='', max_length=100, verbose_name='学院'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stu_card',
            field=models.CharField(default='', max_length=10, verbose_name='学号'),
        ),
    ]
